const AUTH_REFRESH_TOKEN_ACTION = 'CREATE_NEW_PAIRS_OF_TOKENS';
const AUTH_VERIFY_USER_ACTION = 'VERIFY_USER';
const CREATE_USER_FREE_SUBSCRIPTION = 'CREATE_USER_FREE_SUBSCRIPTION';
const SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED';
const FETCH_SUBSCRIPTION_DATA_BY_USER_ID = 'FETCH_SUBSCRIPTION_DATA_BY_USER_ID';
const SUBSCRIPTION_DATA_FETCHED = 'SUBSCRIPTION_DATA_FETCHED';
const EXPORT_NOTIFICATION = 'EXPORT_NOTIFICATION';

module.exports = {
    AUTH_REFRESH_TOKEN_ACTION,
    AUTH_VERIFY_USER_ACTION,
    CREATE_USER_FREE_SUBSCRIPTION,
    SUBSCRIPTION_CREATED,
    FETCH_SUBSCRIPTION_DATA_BY_USER_ID,
    SUBSCRIPTION_DATA_FETCHED,
    EXPORT_NOTIFICATION
};